server:
  port: ${PORT:8080}
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    internal_proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}

management:
  context-path: /admin

spring:
  application:
    name: oauth-proxy
    

#endpoints:
#  restart:
#    enabled: true

security:
  ignored: /favicon.ico, /
  #ignored: /favicon.ico
  basic:
    enabled: false
  user:
    password: none

#https://jmnarloch.wordpress.com/2015/10/21/spring-cloud-eureka-zuul-and-oauth2-scaling-out-authorization-server/
#https://spring.io/blog/2015/11/30/migrating-oauth2-apps-from-spring-boot-1-2-to-1-3    
  oauth2:
    client:
      #client-authentication-scheme: header
      clientId: ${clientId}
      clientSecret: ${clientSecret}
      accessTokenUri: ${loginServiceUrl}/oauth/token
      userAuthorizationUri: ${loginServiceUrl}/oauth/authorize
      scope:
        - openid
      
        
    resource:
      userInfoUri: ${loginServiceUrl}/userinfo #me
      id: openid
      jwt:
#        key-uri: ${uaaServiceUrl}/token_key #https://uaa.<your_domains>/token_key
        key-value: ${jwtKeyValue}
        
#        key-value:  |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2ba4+6dV+B5+uXxZC1pF
#          sshg8j2Aq7ywGr66HkmRCizcwztGgvoJjo6eCnIXElL9kVXxVV0dPP3iiGEgC74K
#          33b5bFONJ3BMOI8Bvr9CSutql6tuu9PM1td0NTD8/+uNWliTdiXleX5tJwaO0xJH
#          NsWEHDLKa6B5mBrzKllb9BCNZVu86R53QN+RncAhitaPxsp0iuff2d7HmJXCmBB7
#          PRF2UPri7q/19Z61DX6xZl1q+WssrI/Zn+HYeZX2qqeaVyQCX2IaUJNjabgBs7QJ
#          ZoYTjqz4Dw71Q2r+UyMWqaVOKKkX5PjOcT8IDjelOXOa3gQG+JvtKM5iKPY8p8Lp
#          nQIDAQAB
#          -----END PUBLIC KEY----- 

zuul:
  routes:
    resources:
      path: /resources/**
      url: ${backend_url}

logging:
  level:
    org.springframework.security: DEBUG


